dist: bionic
language: php

notifications:
  email:
    on_success: never

matrix:
  fast_finish: true
  include:
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config.";

install:
  - mkdir -p build/logs

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - if [[ $(phpenv version-name) != 'nightly' ]]; then composer require --dev php-coveralls/php-coveralls '~2.2' -n ; fi

script:
  - ./bin/phpcs
  - if [[ $(phpenv version-name) != 'nightly' ]]; then ./bin/php-cs-fixer fix --dry-run ; fi;
  - if [[ $(phpenv version-name) != 'nightly' ]]; then phpdbg -qrr bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml ; else ./bin/phpunit ; fi;
  - ./bin/phpstan analyse

after_success:
  - bin/php-coveralls -v --exclude-no-stmt