dist: xenial
language: php
php:
  - '7.3'
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

matrix:
  fast_finish: true

stages:
  - "Code Style Checks"
  - "Test"
  - "Analysis"

jobs:
  include:
    - stage: "Code Style Checks"
      name: "PHP CodeSniffer"
      script: ./bin/phpcs
    - name: "PHP CodeStyle Fixer"
      script: ./bin/php-cs-fixer fix --dry-run
    - stage: Test
      name: "Unit Tests"
      script: ./bin/phpunit --testsuite unit
    - name: "Functional Tests"
      script: ./bin/phpunit --testsuite functional
    - stage: "Analysis"
      name: "Static Analysis"
      script: ./bin/phpstan analyse
