version: '2'

services:
    fpm:
        build: docker/php-fpm
        container_name: demo_fpm
        volumes:
            - ./:/app
        working_dir: /app
        network_mode: bridge

    nginx:
        build: docker/nginx
        container_name: demo_nginx
        volumes:
            - ./:/app
        network_mode: bridge
        ports:
            - "80:80"
        links:
            - fpm

